var customStopWordFilter = function(token) {
  var stopWords = [
      'branch',
    // 'link',
    'app',
    'user',
    'us',
    // 'instal',
    'data',
    'call',
    // 'click',
    // 'referr',
    'custom',
    'want',
    'set',
    // 'dashboard',
    'creat',
    'option',
    'open',
    'see',
    'error',
    'need',
    'sdk',
    'url',
    'key',
    // 'share',
    // 'track',
    // 'paramet',
    'time',
    'requir',
    'object',
    'default',
    'follow',
    'event',
    'exampl',
    'new',
    'deep',
    'add',
    'content',
    // 'first',
    'id',
    'pass',
    'specifi',
    'credit',
    'return',
    // 'getinst',
    'page',
    'up',
    'type',
    'io',
    'method',
    'here',
    'send',
    'through',
    // 'reward',
    'make',
    // 'identifi',
    'code',
    // 'session',
    'sure',
    'string',
    'on',
    'function',
    'refer',
    // 'nserror',
    // 'facebook',
    'tag',
    // 'callback',
    // 'store',
    'allow',
    // 'ad',
    'more',
    // 'param',
    // 'start',
    // 'channel',
    'gener',
    'configur',
    'check',
    'out',
    'note',
    // 'dictionari',
    'inform',
    // 'android',
    'it’',
    'same',
    'specif',
    'system',
    // 'ident',
    // 'web',
    'don’t',
    'show',
    // 'regist',
    'each',
    'featur',
    'valu',
    '2',
    'name',
    // 'initi',
    'we’ll',
    'give',
    'base'
    // 'below'
  ];

      if (stopWords.indexOf(token) === -1) { return token; }
};

module.exports = customStopWordFilter;
